### ISSUE TITLE
Application problem

### ISSUE THREAD

**Issue by IskandarTA** [angelolz/CookieClickerRPC#25] opened 2023-05-21 05:45 UTC
I try to open the app and it immediately closes, what should I do?

**Comment by IskandarTA** [comment] 2023-05-21 05:51
I use steam and I have windows 10, I installed everything that was required, but when I try to open the application it immediately closes

**Comment by angelolz1** [comment] 2023-05-24 15:08
Hello, sorry that you're having this issue.

Have you downloaded the [Java](https://www.java.com/en/download/) application here?

**Comment by IskandarTA** [comment] 2023-05-24 15:29
I get this: Unrecognized option: --version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by IskandarTA** [comment] 2023-05-24 15:32
I did everything that was required, but for some reason, the application immediately closes

**Comment by IskandarTA** [comment] 2023-05-24 16:10
I get this:
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)

**Comment by IskandarTA** [comment] 2023-05-24 16:32
I downloaded "JDK 17" and this is what came out:
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

**Comment by IskandarTA** [comment] 2023-05-24 16:42
but it didn't open again.

**Comment by angelolz1** [comment] 2023-05-24 18:26
Hmm, sorry. I'm not sure why this is happening. I will look into this issue.

You can try downloading the `.jar` file in the release [here](https://github.com/angelolz1/CookieClickerRPC/releases/download/v1.3/CookieClickerRPC-v1.3-NonWindows.jar)

and then run `java -jar <path to jar>/CookieClickerRPC-v1.3-NonWindows.jar`

**Comment by IskandarTA** [comment] 2023-05-24 18:37
It says: Access is denied

**Comment by angelolz1** [comment] 2023-05-24 18:42
If you can't access it, you can go to the repo's home page and click the "Releases" section on the right.

Otherwise, I can work on seeing what the issue is.

**Comment by IskandarTA** [comment] 2023-05-24 18:52
I tried, but nothing worked, does not give access, and also tried to open the application, but nothing worked
Hope you can fix it.

**Comment by angelolz1** [comment] 2023-06-06 05:31
Hello, please see troubleshooting guide [here](https://github.com/angelolz1/CookieClickerRPC#app-closes-instantly-when-i-run-the-app) to fix your problem.

**Comment by angelolz** [comment] 2023-08-21 22:58
No other comment has been posted, so will be closing this issue.

**Closed by angelolz** 2023-08-21 22:58 UTC
